"""Generate codehook source for HTTP API calls.

A codehook receives `{context, slots, defaultInput}` both as a workflow step and as a
`type=function` agent tool (runtime tool_router passes the model's arguments as
`slots`). One template therefore serves both callers. Generating the code from a spec,
rather than letting the model write it, keeps API tools reviewable and free of
accidental credential leaks: secrets are referenced as `{env.NAME}` and stored as
codehook environment variables.
"""
# Shared with botcircuits-agent-builder-copilot (copilot/botcircuits/); keep the two in sync.


import json
import re

_PLACEHOLDER = re.compile(r"\{([A-Za-z_][A-Za-z0-9_.]*)\}")
_METHODS = {"GET", "POST", "PUT", "PATCH", "DELETE"}

_TEMPLATE = """// Generated by botcircuits-agent-builder-copilot. Edit the SPEC, not the plumbing.
const SPEC = __SPEC__;

function lookup(path, scope) {
  if (path.startsWith("env.")) return process.env[path.slice(4)];
  return path.split(".").reduce((v, k) => (v == null ? undefined : v[k]), scope);
}

function fill(template, scope, encode) {
  return template.replace(/\\{([A-Za-z_][A-Za-z0-9_.]*)\\}/g, (match, path) => {
    const value = lookup(path, scope);
    if (value === undefined || value === null) return "";
    const text = typeof value === "object" ? JSON.stringify(value) : String(value);
    return encode ? encodeURIComponent(text) : text;
  });
}

function pick(obj, path) {
  if (!path) return obj;
  return path.replace(/\\[(\\d+)\\]/g, ".$1").split(".").reduce((v, k) => (v == null ? undefined : v[k]), obj);
}

exports.handler = async (event) => {
  const scope = { ...(event.defaultInput || {}), ...(event.slots || {}) };
  const missing = SPEC.required.filter((name) => scope[name] === undefined || scope[name] === "");
  if (missing.length) {
    return { ok: false, error: `Missing required input: ${missing.join(", ")}` };
  }

  const url = new URL(fill(SPEC.url, scope, true));
  for (const [name, value] of Object.entries(SPEC.query)) {
    const filled = fill(value, scope, false);
    if (filled !== "") url.searchParams.set(name, filled);
  }
  const headers = { Accept: "application/json" };
  for (const [name, value] of Object.entries(SPEC.headers)) headers[name] = fill(value, scope, false);

  const init = { method: SPEC.method, headers, signal: AbortSignal.timeout(SPEC.timeoutMs) };
  if (SPEC.body !== null && SPEC.method !== "GET") {
    headers["Content-Type"] = "application/json";
    init.body = fill(SPEC.body, scope, false);
  }

  let response;
  try {
    response = await fetch(url, init);
  } catch (err) {
    return { ok: false, error: `Request failed: ${err.name}` };
  }
  const text = await response.text();
  let data;
  try { data = text ? JSON.parse(text) : null; } catch { data = text.slice(0, 4000); }
  if (!response.ok) {
    return { ok: false, status: response.status, error: typeof data === "string" ? data : data?.message || "error" };
  }

  const result = pick(data, SPEC.resultPath);
  const slots = {};
  for (const [slot, path] of Object.entries(SPEC.slotMapping)) slots[slot] = pick(data, path);
  // `slots` is merged into workflow session slots; agent tools see the whole object.
  return Object.keys(slots).length ? { ok: true, data: result, slots } : { ok: true, data: result };
};
"""


def generate_http_codehook(
    *,
    method: str,
    url: str,
    query: dict[str, str] | None = None,
    headers: dict[str, str] | None = None,
    body_template: str | None = None,
    required_inputs: list[str] | None = None,
    result_path: str = "",
    slot_mapping: dict[str, str] | None = None,
    timeout_ms: int = 15000,
) -> str:
    method = method.upper()
    if method not in _METHODS:
        raise ValueError(f"method must be one of {sorted(_METHODS)}")
    if not url.lower().startswith(("https://", "http://", "{")):
        raise ValueError("url must be an absolute http(s) URL (placeholders allowed)")
    if body_template is not None:
        # Placeholders are filled as raw text, so the template must be valid JSON once filled.
        probe = _PLACEHOLDER.sub("0", body_template)
        try:
            json.loads(probe)
        except json.JSONDecodeError as exc:
            raise ValueError(f"body_template is not valid JSON with placeholders filled: {exc.msg}") from exc
    for value in [url, *(query or {}).values(), *(headers or {}).values()]:
        if re.search(r"(?i)(bearer\s+|(token|key|secret)\s*[:=]\s*)[A-Za-z0-9_\-]{16,}", value or ""):
            raise ValueError("Put credentials in environment variables and reference them as {env.NAME}")
    spec = {
        "method": method,
        "url": url,
        "query": query or {},
        "headers": headers or {},
        "body": body_template,
        "required": required_inputs or [],
        "resultPath": result_path or "",
        "slotMapping": slot_mapping or {},
        "timeoutMs": max(1000, min(int(timeout_ms), 25000)),
    }
    return _TEMPLATE.replace("__SPEC__", json.dumps(spec, indent=2))


def env_references(*templates: str | None) -> set[str]:
    names: set[str] = set()
    for template in templates:
        for path in _PLACEHOLDER.findall(template or ""):
            if path.startswith("env."):
                names.add(path[4:])
    return names
